# Generated by Django 3.2 on 2023-03-22 04:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link_facebook', models.CharField(blank=True, max_length=100)),
                ('link_instagram', models.CharField(blank=True, max_length=100)),
                ('link_twitter', models.CharField(blank=True, max_length=100)),
                ('link_web', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('fecha', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('fecha', models.DateField(blank=True)),
                ('estado', models.CharField(blank=True, default='Sonora', max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=200)),
                ('geo_latitud', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('geo_longitud', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('contiene_imagenes', models.BooleanField(blank=True, default=False)),
                ('notas_internas', models.TextField(blank=True)),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallazgos.colectivo')),
            ],
            options={
                'ordering': ['-source_id'],
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HallazgoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hallazgo/{hallazgo.source_id}')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallazgos.hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='HallazgoCSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='hallazgos_csv', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('uploaded_at', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='modalidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hallazgos.modalidad'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='municipio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hallazgos.municipio'),
        ),
        migrations.CreateModel(
            name='ColectivoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static')),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallazgos.colectivo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hallazgo',
            unique_together={('source_id', 'colectivo')},
        ),
    ]
