# Generated by Django 3.2 on 2023-03-10 07:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link_facebook', models.CharField(blank=True, max_length=100)),
                ('link_instagram', models.CharField(blank=True, max_length=100)),
                ('link_twitter', models.CharField(blank=True, max_length=100)),
                ('link_web', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('fecha', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, default='Sonora', max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=200)),
                ('geo_latitud', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('geo_longitud', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('modalidad', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('contiene_imagenes', models.BooleanField(blank=True, default=False)),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallazgos.colectivo')),
            ],
        ),
        migrations.CreateModel(
            name='HallazgoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallazgos.hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='ColectivoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static')),
                ('colectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallazgos.colectivo')),
            ],
        ),
    ]
