# Generated by Django 3.2 on 2023-03-15 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hallazgos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallazgoCSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='static/hallazgos_csv', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('uploaded_at', models.DateField(verbose_name=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
