# Generated by Django 3.2 on 2023-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgo',
            name='geo_latitud',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='geo_longitud',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
