# Generated by Django 3.2 on 2023-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0002_auto_20230329_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallazgo',
            options={},
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='geo_latitud',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='geo_longitud',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
